### ISSUE TITLE
Non-terminating simulation

### ISSUE THREAD

**Issue by Alden-G878** [jacktreado/dpm#5]
Input: bash submit_bidisperseSinusoidalParticleJamming.sh 16 24 1.1 0.01 10.0  3 day 1-00:0:0 10 1

Base seed: 6

Current runtime: 0-11:0:0
     Max runtime: 1-0:0:0

The simulation is currently running much longer than the others in the same ensemble.  From past experiences, it will likely continue to run until it has reached the limit of one day.  I will update when it has terminated.  Once it has, I will rerun the simulation on the week cluster, to see if the issue is a bug or if the simulation is interesting.

**Comment by Alden-G878** [comment]
The simulation ran until the time limit ran out, with no output written to the .pos file (the record of the simulation was being written, and was in a loop of being overcompressed, similar to before the bug fix). I will rerun this simulation on the week server to see if there is a difference when given more time.

**Comment by jacktreado** [comment]
Hi, can confirm that I found the case where this is happening. I'm going to try to add a routine that checks for a stalled sim, then resets.

**Comment by jacktreado** [comment]
I think it's fixed, now any simulation where `rH` and `rL` get too close, the simulation enters a `stalled` phase and resets the root search variables, decompresses to a nearby state, and tries again. This does not guarantee convergence, but it should improve most stalled cases.

@Alden-G878 I think we can just throw out any simulations that don't converge in a certain time limit, it seems the constant repetition is not so much a bug, just a feature of the very complex energy landscape. And these cases seem to be rare.

Also @tandrewton note this update, if you are using the function `vertexJamming2D` it has some convergence issues, but only occasionally.
